version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    # Dato che è per lo sviluppo, monto la directory locale come volume del Docker container.
    # Questo consentirà di evitare build per ogni modifica
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://backend:3000
    entrypoint: ["npm", "run", "dev"]
