FROM node:18

WORKDIR /usr/src/app

COPY package.json .

RUN npm install -g pnpm
RUN pnpm install

COPY . .

# Expose della porta per il web server API
EXPOSE 3000

# Avvio il web server locale
ENTRYPOINT [ "npx", "nodemon" ]