FROM node:18

WORKDIR /usr/src/app

COPY package.json .

RUN npm install -g pnpm
RUN pnpm install

COPY . .

EXPOSE 4000

# Expose della porta per il web server API
ENTRYPOINT [ "npm", "run", "start", "--", "--port", "4000"]